config/routes.rb
Survey::Application.routes.draw do
  resources :rats

  get "answers/new"

  get "answers/edit"

  resources :custom_fields

  resources :survey_names do 
    resources :questions
    resources :answers 
  end

  devise_for :users

  root :to => "survey_names#index"

end

app/models/rat.rb
class Rat < ActiveRecord::Base
  attr_accessible :address, :name, :phone, :sex
end

app/controllers/rats_controller.rb
class RatsController < ApplicationController
  # GET /rats
  # GET /rats.json
  def index
    @rats = Rat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rats }
    end
  end

  # GET /rats/1
  # GET /rats/1.json
  def show
    @rat = Rat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rat }
    end
  end

  # GET /rats/new
  # GET /rats/new.json
  def new
    @rat = Rat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rat }
    end
  end

  # GET /rats/1/edit
  def edit
    @rat = Rat.find(params[:id])
  end

  # POST /rats
  # POST /rats.json
  def create
    @rat = Rat.new(params[:rat])

    respond_to do |format|
      if @rat.save
        format.html { redirect_to @rat, notice: 'Rat was successfully created.' }
        format.json { render json: @rat, status: :created, location: @rat }
      else
        format.html { render action: "new" }
        format.json { render json: @rat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rats/1
  # PUT /rats/1.json
  def update
    @rat = Rat.find(params[:id])

    respond_to do |format|
      if @rat.update_attributes(params[:rat])
        format.html { redirect_to @rat, notice: 'Rat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rats/1
  # DELETE /rats/1.json
  def destroy
    @rat = Rat.find(params[:id])
    @rat.destroy

    respond_to do |format|
      format.html { redirect_to rats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rats_helper.rb
module RatsHelper
end

app/views/rats/_form.html.erb
<%= form_for @rat, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :phone, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sex, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :sex, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rats_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rats/edit.html.erb
<%- model_class = Rat -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rats/index.html.erb
<%- model_class = Rat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rats.each do |rat| %>
      <tr>
        <td><%= link_to rat.id, rat_path(rat) %></td>
        <td><%= rat.name %></td>
        <td><%= rat.phone %></td>
        <td><%= rat.sex %></td>
        <td><%= rat.address %></td>
        <td><%=l rat.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rat_path(rat), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rat_path(rat),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rat_path,
            :class => 'btn btn-primary' %>

app/views/rats/new.html.erb
<%- model_class = Rat -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rats/show.html.erb
<%- model_class = Rat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @rat.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @rat.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @rat.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @rat.address %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rats_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rat_path(@rat), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rat_path(@rat),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>