config/routes.rb
Survey::Application.routes.draw do
  resources :rats

  get "answers/new"

  get "answers/edit"

  resources :custom_fields

  resources :survey_names do 
    resources :questions
    resources :answers 
  end

  devise_for :users

  root :to => "survey_names#index"

end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  attr_accessible :name
  has_many :questions, dependent: :destroy

  def essay
    "options can't be blank for this type"
  end

  def numeric

  end
  def radiobutton
    false
  end
  def date

  end
  def checkbox
  end
end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  # GET /custom_fields
  # GET /custom_fields.json
  def index
    @custom_fields = CustomField.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @custom_fields }
    end
  end

  # GET /custom_fields/1
  # GET /custom_fields/1.json
  def show
    @custom_field = CustomField.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @custom_field }
    end
  end

  # GET /custom_fields/new
  # GET /custom_fields/new.json
  def new
    @custom_field = CustomField.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @custom_field }
    end
  end

  # GET /custom_fields/1/edit
  def edit
    @custom_field = CustomField.find(params[:id])
  end

  # POST /custom_fields
  # POST /custom_fields.json
  def create
    @custom_field = CustomField.new(params[:custom_field])

    respond_to do |format|
      if @custom_field.save
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully created.' }
        format.json { render json: @custom_field, status: :created, location: @custom_field }
      else
        format.html { render action: "new" }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /custom_fields/1
  # PUT /custom_fields/1.json
  def update
    @custom_field = CustomField.find(params[:id])

    respond_to do |format|
      if @custom_field.update_attributes(params[:custom_field])
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_fields/1
  # DELETE /custom_fields/1.json
  def destroy
    @custom_field = CustomField.find(params[:id])
    @custom_field.destroy

    respond_to do |format|
      format.html { redirect_to custom_fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
end

app/views/custom_fields/_form.html.erb
<%= form_for(@custom_field) do |f| %>
  <% if @custom_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_field.errors.count, "error") %> prohibited this custom_field from being saved:</h2>

      <ul>
      <% @custom_field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_fields/edit.html.erb
<h1>Editing custom_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom_field %> |
<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/index.html.erb
<h1>Listing custom_fields</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @custom_fields.each do |custom_field| %>
  <tr>
    <td><%= custom_field.name %></td>
    <td><%= link_to 'Show', custom_field %></td>
    <td><%= link_to 'Edit', edit_custom_field_path(custom_field) %></td>
    <td><%= link_to 'Destroy', custom_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Custom field', new_custom_field_path %>

app/views/custom_fields/new.html.erb
<h1>New custom_field</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @custom_field.name %>
</p>


<%= link_to 'Edit', edit_custom_field_path(@custom_field) %> |
<%= link_to 'Back', custom_fields_path %>