config/routes.rb
Survey::Application.routes.draw do
  resources :rats

  get "answers/new"

  get "answers/edit"

  resources :custom_fields

  resources :survey_names do 
    resources :questions
    resources :answers 
  end

  devise_for :users

  root :to => "survey_names#index"

end

app/models/survey_name.rb
class SurveyName < ActiveRecord::Base
  attr_accessible :name
  has_many :questions, dependent: :destroy
  has_many :answers,dependent: :destroy
end

app/controllers/survey_names_controller.rb
class SurveyNamesController < ApplicationController
  # GET /survey_names
  # GET /survey_names.json
  def index
    @survey_names = SurveyName.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @survey_names }
    end
  end

  # GET /survey_names/1
  # GET /survey_names/1.json
  def show
    @survey_name = SurveyName.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey_name }
    end
  end

  # GET /survey_names/new
  # GET /survey_names/new.json
  def new
    @survey_name = SurveyName.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey_name }
    end
  end

  # GET /survey_names/1/edit
  def edit
    @survey_name = SurveyName.find(params[:id])
  end

  # POST /survey_names
  # POST /survey_names.json
  def create
    @survey_name = SurveyName.new(params[:survey_name])

    respond_to do |format|
      if @survey_name.save
        format.html { redirect_to @survey_name, notice: 'Survey name was successfully created.' }
        format.json { render json: @survey_name, status: :created, location: @survey_name }
      else
        format.html { render action: "new" }
        format.json { render json: @survey_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /survey_names/1
  # PUT /survey_names/1.json
  def update
    @survey_name = SurveyName.find(params[:id])

    respond_to do |format|
      if @survey_name.update_attributes(params[:survey_name])
        format.html { redirect_to @survey_name, notice: 'Survey name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_names/1
  # DELETE /survey_names/1.json
  def destroy
    @survey_name = SurveyName.find(params[:id])
    @survey_name.destroy

    respond_to do |format|
      format.html { redirect_to survey_names_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/survey_names_helper.rb
module SurveyNamesHelper
end

app/views/survey_names/_form.html.erb
<%= form_for(@survey_name) do |f| %>
  <% if @survey_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_name.errors.count, "error") %> prohibited this survey_name from being saved:</h2>

      <ul>
      <% @survey_name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/survey_names/edit.html.erb
<h1>Editing survey_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_name %> |
<%= link_to 'Back', survey_names_path %>

app/views/survey_names/index.html.erb
<h1>Listing survey_names</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @survey_names.each do |survey_name| %>
  <tr>
    <td><%= survey_name.name %></td>
    <td><%= link_to 'Show', survey_name %></td>
    <td><%= link_to 'Edit', edit_survey_name_path(survey_name) %></td>
    <td><%= link_to 'Destroy', survey_name, method: :delete, data: { confirm: 'Are you sure?' } %> |</td>
    <td><%= link_to "Take Survey" , new_survey_name_answer_path(survey_name) %> |</td>
    <td><%= link_to 'Results', survey_name_questions_path(survey_name) %></td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Survey name', new_survey_name_path %>

app/views/survey_names/new.html.erb
<h1>New survey_name</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_names_path %>

app/views/survey_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey_name.name %>
</p>

<br />
<% @survey_name.questions.all.each do |que| %>
<%= que.name %>
<%= que.custom_field.name %>
<%= link_to 'edit',edit_survey_name_question_path(@survey_name, que) %>
<br />
<% end %>

<%= link_to "Questions" ,new_survey_name_question_path(@survey_name) %> |

<%= link_to 'Edit', edit_survey_name_path(@survey_name) %> |
<%= link_to 'Back', survey_names_path %>